---
apiVersion: v1
kind: Service
metadata:
  name: service-openwire
  namespace: amqbroker-dev
spec:
  type: NodePort
  ports:
    - port: 61616
      targetPort: 61616
      protocol: TCP
      name: openwire
      nodePort: 30616 
  selector:
    ActiveMQArtemis: dev
    application: dev-app
    
---
apiVersion: v1
kind: Service
metadata:
  name: service-amqp
  namespace: amqbroker-dev
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
      nodePort: 30672 
  selector:
    ActiveMQArtemis: dev
    application: dev-app
