# Artemis instance that enables SSL and configure the certs created by cert-manger for the OpenWire Acceptor
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: dev
  namespace: amqbroker-dev
spec:
  # Don't expose acceptors as we want to load-balance, hence we need to create our own route
  # The default route mechanism is creating one route per broker
  # Enable SSL
  acceptors:
      # if expose true, one route per broker is created
      # if we want routes that balance traffic between the brokers, create the route manually, together with the service 
    - expose: false
      name: openwire
      port: 61616
      protocols: openwire
      # SSL
      sslEnabled: true
      # SSL
      sslSecret: broker-cert-openwire-secret
      # don't expose routes   
    - expose: false
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
  addressSettings:
    addressSetting:
      - deadLetterAddress: foo.dlq
        match: foo
        maxDeliveryAttempts: 5
        maxSizeBytes: 2Mb
  adminPassword: password
  adminUser: admin
  brokerProperties:
    # Autoreload when certificate changes
    - acceptorConfigurations."openwire".params.sslAutoReload=true
    - addressConfigurations."foo".routingTypes=ANYCAST
    - addressConfigurations."foo".queueConfigs."foo".routingType=ANYCAST
    - addressConfigurations."foo.dlq".routingTypes=ANYCAST
    - addressConfigurations."foo.dlq".queueConfigs."foo.dlq".routingType=ANYCAST
    - addressConfigurations."bar".routingTypes=MULTICAST
    - securityRoles.foo.toms.send=true
    - securityRoles.foo.toms.receive=true
    - securityRoles."mops.address.foo.*".toms.view=true
    - securityRoles."mops.address.foo.*".toms.edit=true
    - securityRoles."mops.#".admins.view=true
    - securityRoles."mops.#".admins.edit=true
    - securityRoles."mops.broker.forceFailover".denied=-
  console:
    expose: true
  deploymentPlan:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: ActiveMQArtemis
                    operator: In
                    values:
                      - dev
              topologyKey: kubernetes.io/hostname
            weight: 100
    clustered: true
    extraMounts:
      secrets:
        - custom-jaas-config
    image: placeholder
    messageMigration: true
    persistenceEnabled: true
    requireLogin: true
    size: 2
  env:
    - name: JAVA_ARGS_APPEND
      value: '-Dhawtio.role=* -Djavax.management.builder.initial=org.apache.activemq.artemis.core.server.management.ArtemisRbacMBeanServerBuilder'
