kind: Secret
apiVersion: v1
metadata:
  name: custom-jaas-config
  namespace: amqbroker-dev
stringData:
  login.config: |-
    activemq {
       org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=true
          org.apache.activemq.jaas.properties.user="new-users.properties"
          org.apache.activemq.jaas.properties.role="new-roles.properties";
    
       org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=false
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties"
          baseDir="/home/jboss/amq-broker/etc";
    };
  new-roles.properties: |-
    admins=tom, joe
    toms=tom
    joes=joes
  new-users.properties: |- 
    tom=tom01!
    joe=joe01!
